### ISSUE TITLE
Add command to fetch list of contributors

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-community#10]
Mattermost sends mugs to new contributors. To help automating this process a `/community new-committer` command should be added. It should be run like this:
`/community new-committer mattermost 2020-01-01` and should return a list of all new committers since the given date. A committer is a github user that added a commit to any repository inside of the organisation `mattermost`.

The returned list show contain the username, link to the first commit and the date of the first commit.

**Comment by hanzei** [comment]
*@hanzei attached a* [message](https://community-release.mattermost.com/core/pl/3oqaot335idipkmch3oj3tgxze) *from @jason.blais*
@hanzei @hanna.park  In the next two weeks, if you have time, can you help update the [mattermost contributors page](https://developers.mattermost.com/contribute/team_contributions/) to have one list of contributors with the first date of their contribution? In particular, no individual repositories listed, just have everyone in one list.

I've started a PR of of what this list would look like based on server/webapp contributors, but needs the addition of first-time contributors from other repositories as well: [pr-mattermost-developer-documentation-570](https://github.com/mattermost/mattermost-developer-documentation/pull/570)

**Comment by GrigalashviliT** [comment]
Hi, I want to work on this

**Comment by hanzei** [comment]
That would be awesome, thanks @GrigalashviliT :tada:
