### ISSUE TITLE
/community commiter fails for non-organisation repositories 

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-community#15]

**Comment by rahulchheda** [comment]
hi @hanzei, it seems like an interesting issue, I would like to take this up. Could you help me explain what does a `non-organization repo` means with an example? For eg: If I create a new repo right now, the organization is set to my GitHub ID. So, if you could expand this that would be great.
Any steps to reproduce would also be appreciated.

**Comment by hanzei** [comment]
First: Thanks for taking a look at this issue @rahulchheda :+1: A `non-organisation repo` is a repo that is associated with a GitHub account and not with an organisation. E.g. https://github.com/hanzei/plugin-test/ is such repo.

Does this help?

**Comment by rahulchheda** [comment]
@hanzei Could you help me set developer environment for setup?

**Comment by hanzei** [comment]
Sure. https://developers.mattermost.com/contribute/server/developer-setup/ covers the steps to setup a developers environment. If you have any specific questions, please join the [Mattermost Community Server](https://community.mattermost.com) and ping me in `~peer-to-peer-help`.
