### ISSUE TITLE
Channel/All mentions are not working after enabling the plugin

### ISSUE THREAD

**Issue by Shubhamchinda** [mattermost/mattermost-plugin-community#22]
**What**
---
I create a plugin to edit/handle a special case in mm-posts by using MM registry web reference helper function [registerPostTypeComponent](https://developers.mattermost.com/extend/plugins/webapp/reference/#registerPostTypeComponent) to manipulate the posts in mattermost.

But the channel mentions are not working properly. Please see the image :

![Screenshot from 2020-08-05 16-12-08](https://user-images.githubusercontent.com/21038543/89411248-bef8a100-d742-11ea-8598-5ea655b9a7eb.jpg)

On [this page](https://developers.mattermost.com/extend/plugins/webapp/reference/) under `formatText` section it is specified the `siteUrl` is required, but its not working. 

I'm not really sure why this is not working.

If anybody could help. That'd be great.
Thanks

**Comment by hanzei** [comment]
Hey @Shubhamchinda,

Would you please join the [Mattermost Community Server](https://community.mattermost.com) and ask your questions in the `Peer-to-peer Help` channel? This repository is tied to a specific plugin, not general questions or support.

**Comment by Shubhamchinda** [comment]
Ohh Okayy... @hanzei . Thanks!
