### ISSUE TITLE
/contributors command should have the order case insensitive

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-community#4]
Propose having the output of the /contributors command case insensitive.

Repro: Post `/contributors mattermost all 2019-04-01 2019-04-30`

Observed: `ThiefMaster` ordered before `akrfjmt`

Expected: `ThiefMaster` ordered after `akrfjmt`

Note: Another example for the order would be `carlos1, Carlos2, carlos3`.

**Comment by hanzei** [comment]
Fixed in https://github.com/mattermost/mattermost-plugin-community/releases/tag/v0.1.0
